# Generated by Django 3.2.6 on 2021-08-04 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20210804_2141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasksscheduler',
            name='best_schedule',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tasksscheduler',
            name='raw_tasks',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
